---
version: "3"
services:

  server1:
    image: example/web:latest
    build:
      context: web
    environment:
    - "name=server1"

  haproxy:
    image: haproxytech/haproxy-ubuntu:2.3
    volumes:
    - "./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg"
    - "./haproxy/cors.lua:/etc/haproxy/cors.lua"
    ports:
    - "80:80"
    - "8080:8080"
    - "9000:9000"
    depends_on:
    - server1